# Generated by Django 3.2.5 on 2022-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_ticket_has_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
    ]
