# Generated by Django 4.0.6 on 2022-07-28 17:03

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_review = Permission.objects.get(codename='add_review')
    change_review = Permission.objects.get(codename='change_review')
    delete_review = Permission.objects.get(codename='delete_review')

    add_ticket = Permission.objects.get(codename='add_ticket')
    change_ticket = Permission.objects.get(codename='change_ticket')
    delete_ticket = Permission.objects.get(codename='delete_ticket')

    creator_permissions = [
        add_review,
        change_review,
        delete_review,
        add_ticket,
        change_ticket,
        delete_ticket,

    ]

    creators = Group(name='creators')
    creators.save()
    creators.permissions.set(creator_permissions)

    for user in User.objects.all():
        creators.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
